#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hamepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /course
    permanent: true